services:
  - xvfb
addons:
  firefox: "49.0.2"
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=django111
  - DJANGO=django20
  - DJANGO=django21
  - DJANGO=django22
jobs:
  exclude:
    - python: "2.7"
      env: DJANGO=django20
    - python: "2.7"
      env: DJANGO=django21
    - python: "2.7"
      env: DJANGO=django22
before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO
after_success:
  - codecov
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
